In [13]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.13/dist-packages (40.39.0)

In [14]:
from faker import Faker
import pandas as pd
import random

fake = Faker()

In [15]:
num_apps = 1000

applications = []

for i in range(num_apps):

    app = {
        "application_id": f"APP{i+1:03d}",
        "application_name": fake.bs(),
        "cpu_usage": round(random.uniform(0.1, 1.0), 2),
        "memory_usage": round(random.uniform(0.1, 1.0), 2),
        "age_years": random.randint(1, 15),
        "criticality": random.choice(["Low", "Medium", "High"]),
        "compliance_flag": random.choice([0, 1])
    }

    applications.append(app)

df = pd.DataFrame(applications)

df.head()

,application_id,application_name,cpu_usage,memory_usage,age_years,criticality,compliance_flag
0,APP001,incentivize holistic bandwidth,0.76,0.64,15,Low,0
1,APP002,incentivize intuitive e-commerce,0.90,0.19,14,Low,1
2,APP003,incubate robust info-mediaries,0.51,0.82,2,Low,0
3,APP004,re-contextualize scalable mindshare,0.44,0.92,13,High,0
4,APP005,extend 24/365 e-commerce,0.49,0.71,10,Low,1

In [16]:
app_ids = df["application_id"].tolist()

dependency_ids = []

for app_id in app_ids:

    possible_dependencies = [
        x for x in app_ids
        if x != app_id
    ]

    num_dependencies = random.randint(0, 5)

    dependencies = random.sample(
        possible_dependencies,
        min(num_dependencies, len(possible_dependencies))
    )

    dependency_ids.append(",".join(dependencies))

df["dependency_ids"] = dependency_ids

# Replace empty dependency values with 0
df["dependency_ids"] = df["dependency_ids"].replace("", 0)

df["dependency_count"] = df["dependency_ids"].apply(
    lambda x: 0 if x == 0 else len(x.split(","))
)

df.head()

,application_id,application_name,cpu_usage,memory_usage,age_years,criticality,compliance_flag,dependency_ids,dependency_count
0,APP001,incentivize holistic bandwidth,0.76,0.64,15,Low,0,"APP089,APP635,APP387,APP766,APP049",5
1,APP002,incentivize intuitive e-commerce,0.90,0.19,14,Low,1,0,0
2,APP003,incubate robust info-mediaries,0.51,0.82,2,Low,0,"APP391,APP198",2
3,APP004,re-contextualize scalable mindshare,0.44,0.92,13,High,0,"APP723,APP696,APP980,APP264,APP1000",5
4,APP005,extend 24/365 e-commerce,0.49,0.71,10,Low,1,"APP896,APP208,APP924",3

In [17]:
df.to_csv(
    "application_portfolio.csv",
    index=False
)

In [18]:
df.shape

(1000, 9)