In [7]:
!pip install faker

Requirement already satisfied: faker in /usr/local/lib/python3.13/dist-packages (40.39.0)

In [8]:
from faker import Faker
import pandas as pd
import random

fake = Faker()

In [9]:
num_apps = 700

applications = []

for i in range(num_apps):

    app = {
        "application_id": f"APP{i+1:03d}",
        "application_name": fake.bs(),
        "cpu_usage": round(random.uniform(0.1, 1.0), 2),
        "memory_usage": round(random.uniform(0.1, 1.0), 2),
        "age_years": random.randint(1, 15),
        "criticality": random.choice(["Low", "Medium", "High"]),
        "compliance_flag": random.choice([0, 1])
    }

    applications.append(app)

df = pd.DataFrame(applications)

df.head()

,application_id,application_name,cpu_usage,memory_usage,age_years,criticality,compliance_flag
0,APP001,re-intermediate rich schemas,0.40,0.10,6,Low,0
1,APP002,extend revolutionary interfaces,0.65,0.78,11,Medium,1
2,APP003,whiteboard scalable paradigms,0.20,0.68,9,High,1
3,APP004,implement transparent web-readiness,0.35,0.24,5,Low,0
4,APP005,morph open-source e-tailers,0.52,0.21,1,Medium,0

In [10]:
app_ids = df["application_id"].tolist()

dependency_ids = []

for app_id in app_ids:

    possible_dependencies = [
        x for x in app_ids
        if x != app_id
    ]

    num_dependencies = random.randint(0, 5)

    dependencies = random.sample(
        possible_dependencies,
        min(num_dependencies, len(possible_dependencies))
    )

    dependency_ids.append(",".join(dependencies))

df["dependency_ids"] = dependency_ids

# Replace empty dependency values with 0
df["dependency_ids"] = df["dependency_ids"].replace("", 0)

df["dependency_count"] = df["dependency_ids"].apply(
    lambda x: 0 if x == 0 else len(x.split(","))
)

df.head()

,application_id,application_name,cpu_usage,memory_usage,age_years,criticality,compliance_flag,dependency_ids,dependency_count
0,APP001,re-intermediate rich schemas,0.40,0.10,6,Low,0,"APP599,APP341,APP610,APP583",4
1,APP002,extend revolutionary interfaces,0.65,0.78,11,Medium,1,"APP105,APP197",2
2,APP003,whiteboard scalable paradigms,0.20,0.68,9,High,1,"APP157,APP230",2
3,APP004,implement transparent web-readiness,0.35,0.24,5,Low,0,"APP140,APP355,APP660",3
4,APP005,morph open-source e-tailers,0.52,0.21,1,Medium,0,"APP013,APP345,APP220,APP475,APP635",5

In [11]:
df.to_csv(
    "application_portfolio.csv",
    index=False
)

In [12]:
df.shape

(700, 9)