In [2]:
!tar -xzf migration_data.tar.gz

In [4]:
!ls -lh

total 92M
drwxrwxr-x 2 ubuntu ubuntu 4.0K Sep 16 18:58 machine_events
-rw-r--r-- 1 root   root    92M Sep 16 19:03 migration_data.tar.gz
drwxr-xr-x 1 root   root   4.0K Sep  4 13:25 sample_data
drwxrwxr-x 2 ubuntu ubuntu 4.0K Sep 16 18:56 task_events
drwxrwxr-x 2 ubuntu ubuntu 4.0K Sep 16 18:55 task_usage

In [6]:
!find task_usage task_events machine_events -type f

task_usage/part-00000-of-00500.csv.gz
task_events/part-00000-of-00500.csv.gz
machine_events/part-00000-of-00001.csv.gz

In [7]:
import pandas as pd

task_usage = pd.read_csv(
    "task_usage/part-00000-of-00500.csv.gz",
    header=None
)

print("Rows:", len(task_usage))
print("Columns:", len(task_usage))

task_usage.head()

Rows: 2520773
Columns: 2520773

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,600000000,900000000,3418309,0,4155527081,0.001562,0.06787,0.07568,0.001156,0.001503,0.06787,0.000003,0.000187,0.039670,0.000357,2.445,0.007243,0,1,0.0
1,600000000,900000000,3418309,1,329150663,0.001568,0.06787,0.07556,0.000320,0.000700,0.06787,0.000006,0.000188,0.033020,0.000929,2.100,0.005791,0,1,0.0
2,600000000,900000000,3418314,0,3938719206,0.000307,0.08044,0.09521,0.000282,0.000670,0.08044,0.000005,0.000184,0.023770,0.000786,5.588,0.020800,0,1,0.0
3,600000000,900000000,3418314,1,351618647,0.000300,0.08044,0.09521,0.000537,0.000870,0.08044,0.000010,0.000183,0.007919,0.002285,5.198,0.020380,0,1,0.0
4,600000000,900000000,3418319,0,431052910,0.000461,0.07715,0.08740,0.000625,0.000852,0.07715,0.000002,0.000204,0.005112,0.000215,2.937,0.009449,0,1,0.0

In [8]:
import gzip

file_path = "task_usage/part-00000-of-00500.csv.gz"

with gzip.open(file_path, "rt") as f:
    first_line = f.readline()

print(first_line)

600000000,900000000,3418309,0,4155527081,0.001562,0.06787,0.07568,0.001156,0.001503,0.06787,2.861e-06,0.0001869,0.03967,0.0003567,2.445,0.007243,0,1,0

In [10]:
import pandas as pd

task_usage = pd.read_csv(
    "task_usage/part-00000-of-00500.csv.gz",
    header=None
)

print("Rows:", task_usage.shape[0])
print("Columns:", task_usage.shape[1])
task_usage.head()

Rows: 2520773
Columns: 20

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,600000000,900000000,3418309,0,4155527081,0.001562,0.06787,0.07568,0.001156,0.001503,0.06787,0.000003,0.000187,0.039670,0.000357,2.445,0.007243,0,1,0.0
1,600000000,900000000,3418309,1,329150663,0.001568,0.06787,0.07556,0.000320,0.000700,0.06787,0.000006,0.000188,0.033020,0.000929,2.100,0.005791,0,1,0.0
2,600000000,900000000,3418314,0,3938719206,0.000307,0.08044,0.09521,0.000282,0.000670,0.08044,0.000005,0.000184,0.023770,0.000786,5.588,0.020800,0,1,0.0
3,600000000,900000000,3418314,1,351618647,0.000300,0.08044,0.09521,0.000537,0.000870,0.08044,0.000010,0.000183,0.007919,0.002285,5.198,0.020380,0,1,0.0
4,600000000,900000000,3418319,0,431052910,0.000461,0.07715,0.08740,0.000625,0.000852,0.07715,0.000002,0.000204,0.005112,0.000215,2.937,0.009449,0,1,0.0

In [11]:
task_usage.columns = [
    "start_time",
    "end_time",
    "job_id",
    "task_index",
    "machine_id",
    "cpu_rate",
    "canonical_memory_usage",
    "assigned_memory_usage",
    "unmapped_page_cache",
    "total_page_cache",
    "max_memory_usage",
    "mean_disk_io_time",
    "mean_local_disk_space",
    "max_cpu_rate",
    "max_disk_io_time",
    "cpi",
    "mai",
    "sampling_portion",
    "aggregation_type",
    "sampled_cpu_usage"
]

task_usage.head()

,start_time,end_time,job_id,task_index,machine_id,cpu_rate,canonical_memory_usage,assigned_memory_usage,unmapped_page_cache,total_page_cache,max_memory_usage,mean_disk_io_time,mean_local_disk_space,max_cpu_rate,max_disk_io_time,cpi,mai,sampling_portion,aggregation_type,sampled_cpu_usage
0,600000000,900000000,3418309,0,4155527081,0.001562,0.06787,0.07568,0.001156,0.001503,0.06787,0.000003,0.000187,0.039670,0.000357,2.445,0.007243,0,1,0.0
1,600000000,900000000,3418309,1,329150663,0.001568,0.06787,0.07556,0.000320,0.000700,0.06787,0.000006,0.000188,0.033020,0.000929,2.100,0.005791,0,1,0.0
2,600000000,900000000,3418314,0,3938719206,0.000307,0.08044,0.09521,0.000282,0.000670,0.08044,0.000005,0.000184,0.023770,0.000786,5.588,0.020800,0,1,0.0
3,600000000,900000000,3418314,1,351618647,0.000300,0.08044,0.09521,0.000537,0.000870,0.08044,0.000010,0.000183,0.007919,0.002285,5.198,0.020380,0,1,0.0
4,600000000,900000000,3418319,0,431052910,0.000461,0.07715,0.08740,0.000625,0.000852,0.07715,0.000002,0.000204,0.005112,0.000215,2.937,0.009449,0,1,0.0

In [12]:
task_usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2520773 entries, 0 to 2520772
Data columns (total 20 columns):
 #   Column                  Dtype
---  ------                  -----
 0   start_time              int64
 1   end_time                int64
 2   job_id                  int64
 3   task_index              int64
 4   machine_id              int64
 5   cpu_rate                float64
 6   canonical_memory_usage  float64
 7   assigned_memory_usage   float64
 8   unmapped_page_cache     float64
 9   total_page_cache        float64
 10  max_memory_usage        float64
 11  mean_disk_io_time       float64
 12  mean_local_disk_space   float64
 13  max_cpu_rate            float64
 14  max_disk_io_time        float64
 15  cpi                     float64
 16  mai                     float64
 17  sampling_portion        int64
 18  aggregation_type        int64
 19  sampled_cpu_usage       float64
dtypes: float64(13), int64(7)
memory usage: 384.6 MB

In [13]:
print(task_usage.columns.tolist())

['start_time', 'end_time', 'job_id', 'task_index', 'machine_id', 'cpu_rate', 'canonical_memory_usage', 'assigned_memory_usage', 'unmapped_page_cache', 'total_page_cache', 'max_memory_usage', 'mean_disk_io_time', 'mean_local_disk_space', 'max_cpu_rate', 'max_disk_io_time', 'cpi', 'mai', 'sampling_portion', 'aggregation_type', 'sampled_cpu_usage']

In [14]:
print(task_usage[["start_time", "end_time", "job_id", "task_index", "machine_id"]].head())

   start_time   end_time   job_id  task_index  machine_id
0   600000000  900000000  3418309           0  4155527081
1   600000000  900000000  3418309           1   329150663
2   600000000  900000000  3418314           0  3938719206
3   600000000  900000000  3418314           1   351618647
4   600000000  900000000  3418319           0   431052910

In [15]:
print(task_usage[[
    "start_time",
    "end_time",
    "job_id",
    "task_index",
    "machine_id"
]].head(10))

   start_time   end_time   job_id  task_index  machine_id
0   600000000  900000000  3418309           0  4155527081
1   600000000  900000000  3418309           1   329150663
2   600000000  900000000  3418314           0  3938719206
3   600000000  900000000  3418314           1   351618647
4   600000000  900000000  3418319           0   431052910
5   600000000  900000000  3418319           1   257348783
6   600000000  900000000  3418324           0  5655258253
7   600000000  900000000  3418324           1  3550322224
8   600000000  900000000  3418329           0     1303745
9   600000000  900000000  3418329           1  3894543095

In [16]:
print(task_usage.dtypes)

start_time                  int64
end_time                    int64
job_id                      int64
task_index                  int64
machine_id                  int64
cpu_rate                  float64
canonical_memory_usage    float64
assigned_memory_usage     float64
unmapped_page_cache       float64
total_page_cache          float64
max_memory_usage          float64
mean_disk_io_time         float64
mean_local_disk_space     float64
max_cpu_rate              float64
max_disk_io_time          float64
cpi                       float64
mai                       float64
sampling_portion            int64
aggregation_type            int64
sampled_cpu_usage         float64
dtype: object

In [17]:
missing = task_usage.isnull().sum()

print(missing)

start_time                     0
end_time                       0
job_id                         0
task_index                     0
machine_id                     0
cpu_rate                       0
canonical_memory_usage         0
assigned_memory_usage          0
unmapped_page_cache            0
total_page_cache               0
max_memory_usage               0
mean_disk_io_time              0
mean_local_disk_space          0
max_cpu_rate                   0
max_disk_io_time          103489
cpi                       270770
mai                       412598
sampling_portion               0
aggregation_type               0
sampled_cpu_usage              0
dtype: int64

In [18]:
missing_percent = (task_usage.isnull().sum() / len(task_usage)) * 100

print(missing_percent[missing_percent > 0])

max_disk_io_time     4.105447
cpi                 10.741546
mai                 16.367916
dtype: float64

In [19]:
for col in ["max_disk_io_time", "cpi", "mai"]:
    print("\n", col)
    print(task_usage[col].describe())

 max_disk_io_time
count    2.417284e+06
mean     1.792180e-02
std      6.525398e-02
min      0.000000e+00
25%      1.431000e-04
50%      1.358000e-03
75%      1.036000e-02
max      1.811000e+00
Name: max_disk_io_time, dtype: float64

 cpi
count    2.250003e+06
mean     4.648879e+00
std      5.521553e+00
min      7.136000e-02
25%      1.931000e+00
50%      3.187000e+00
75%      4.353000e+00
max      1.599000e+03
Name: cpi, dtype: float64

 mai
count    2.108175e+06
mean     1.632551e-02
std      2.604191e-02
min      1.090000e-07
25%      3.797000e-03
50%      8.371000e-03
75%      1.355000e-02
max      2.000000e+00
Name: mai, dtype: float64

In [20]:
important_cols = [
    "cpu_rate",
    "canonical_memory_usage",
    "assigned_memory_usage",
    "mean_disk_io_time",
    "mean_local_disk_space",
    "max_cpu_rate"
]

print(task_usage[important_cols].describe())

           cpu_rate  canonical_memory_usage  assigned_memory_usage  \
count  2.520773e+06            2.520773e+06           2.520773e+06
mean   1.745433e-02            1.904362e-02           2.389051e-02
std    3.560218e-02            3.386104e-02           3.903339e-02
min    0.000000e+00            0.000000e+00           0.000000e+00
25%    1.936000e-04            6.104000e-04           1.934000e-03
50%    1.221000e-03            4.425000e-03           7.744000e-03
75%    1.981000e-02            2.167000e-02           2.893000e-02
max    5.332000e-01            7.520000e-01           7.588000e-01

       mean_disk_io_time  mean_local_disk_space  max_cpu_rate
count       2.520773e+06           2.520773e+06  2.520773e+06
mean        2.410188e-03           9.700038e-05  7.022991e-02
std         1.531462e-02           2.316689e-04  1.084387e-01
min         0.000000e+00           0.000000e+00  0.000000e+00
25%         1.907000e-06           9.537000e-07  7.229000e-04
50%         1.240000e-05           1.812000e-05  1.581000e-02
75%         1.993000e-04           1.268000e-04  1.046000e-01
max         5.830000e-01           7.256000e-03  1.436000e+01

In [21]:
migration_data = task_usage.copy()

print("Original rows:", len(task_usage))
print("Working rows:", len(migration_data))
print("Working columns:", len(migration_data.columns))

Original rows: 2520773
Working rows: 2520773
Working columns: 20

In [22]:
migration_data = migration_data[
    [
        "start_time",
        "end_time",
        "job_id",
        "task_index",
        "machine_id",
        "cpu_rate",
        "canonical_memory_usage",
        "assigned_memory_usage",
        "unmapped_page_cache",
        "total_page_cache",
        "max_memory_usage",
        "mean_disk_io_time",
        "mean_local_disk_space",
        "max_cpu_rate",
        "sampling_portion",
        "aggregation_type",
        "sampled_cpu_usage"
    ]
].copy()

print("Rows:", migration_data.shape[0])
print("Columns:", migration_data.shape[1])
print(migration_data.columns.tolist())

Rows: 2520773
Columns: 17
['start_time', 'end_time', 'job_id', 'task_index', 'machine_id', 'cpu_rate', 'canonical_memory_usage', 'assigned_memory_usage', 'unmapped_page_cache', 'total_page_cache', 'max_memory_usage', 'mean_disk_io_time', 'mean_local_disk_space', 'max_cpu_rate', 'sampling_portion', 'aggregation_type', 'sampled_cpu_usage']

In [24]:
duplicate_count = migration_data.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 2

In [25]:
before = len(migration_data)

migration_data = migration_data.drop_duplicates().copy()

after = len(migration_data)

print("Rows before:", before)
print("Rows after:", after)
print("Duplicates removed:", before - after)

Rows before: 2520773
Rows after: 2520771
Duplicates removed: 2

In [27]:
numeric_cols = [
    "cpu_rate",
    "canonical_memory_usage",
    "assigned_memory_usage",
    "unmapped_page_cache",
    "total_page_cache",
    "max_memory_usage",
    "mean_disk_io_time",
    "mean_local_disk_space",
    "max_cpu_rate",
    "sampled_cpu_usage"
]

negative_values = (migration_data[numeric_cols] < 0).sum()

print(negative_values)

cpu_rate                  0
canonical_memory_usage    0
assigned_memory_usage     0
unmapped_page_cache       0
total_page_cache          0
max_memory_usage          0
mean_disk_io_time         0
mean_local_disk_space     0
max_cpu_rate              0
sampled_cpu_usage         0
dtype: int64

In [28]:
interval_seconds = (
    migration_data["end_time"] - migration_data["start_time"]
) / 1_000_000

print(interval_seconds.describe())

count    2.520771e+06
mean     2.698730e+02
std      8.282639e+01
min      1.000000e+00
25%      3.000000e+02
50%      3.000000e+02
75%      3.000000e+02
max      3.000000e+02
dtype: float64

In [29]:
migration_data["duration_seconds"] = (
    migration_data["end_time"] - migration_data["start_time"]
) / 1_000_000

print(migration_data[
    ["start_time", "end_time", "duration_seconds"]
].head())

   start_time   end_time  duration_seconds
0   600000000  900000000             300.0
1   600000000  900000000             300.0
2   600000000  900000000             300.0
3   600000000  900000000             300.0
4   600000000  900000000             300.0

In [30]:
migration_data["time_hours"] = (
    migration_data["start_time"] - migration_data["start_time"].min()
) / 3_600_000_000

print(migration_data[
    ["start_time", "time_hours"]
].head(10))

   start_time  time_hours
0   600000000         0.0
1   600000000         0.0
2   600000000         0.0
3   600000000         0.0
4   600000000         0.0
5   600000000         0.0
6   600000000         0.0
7   600000000         0.0
8   600000000         0.0
9   600000000         0.0

In [31]:
print("Unique jobs:", migration_data["job_id"].nunique())
print("Unique tasks:", migration_data["task_index"].nunique())
print("Unique machines:", migration_data["machine_id"].nunique())

Unique jobs: 4852
Unique tasks: 20010
Unique machines: 12478

In [32]:
migration_data["task_id"] = (
    migration_data["job_id"].astype(str)
    + "_"
    + migration_data["task_index"].astype(str)
)

print(migration_data[
    ["job_id", "task_index", "task_id"]
].head(10))

    job_id  task_index    task_id
0  3418309           0  3418309_0
1  3418309           1  3418309_1
2  3418314           0  3418314_0
3  3418314           1  3418314_1
4  3418319           0  3418319_0
5  3418319           1  3418319_1
6  3418324           0  3418324_0
7  3418324           1  3418324_1
8  3418329           0  3418329_0
9  3418329           1  3418329_1

In [33]:
print("Unique task IDs:", migration_data["task_id"].nunique())
print("Total rows:", len(migration_data))

Unique task IDs: 179427
Total rows: 2520771

In [34]:
task_record_counts = migration_data.groupby("task_id").size()

print(task_record_counts.describe())

count    179427.000000
mean         14.049006
std           5.639122
min           1.000000
25%           9.500000
50%          17.000000
75%          17.000000
max         429.000000
dtype: float64

In [35]:
print("Minimum time (hours):", migration_data["time_hours"].min())
print("Maximum time (hours):", migration_data["time_hours"].max())
print("Approximate coverage (days):", migration_data["time_hours"].max() / 24)

Minimum time (hours): 0.0
Maximum time (hours): 1.3919444444444444
Approximate coverage (days): 0.05799768518518519

In [36]:
print("CPU rate:")
print(migration_data["cpu_rate"].describe())

print("\nCanonical memory:")
print(migration_data["canonical_memory_usage"].describe())

print("\nMax CPU rate:")
print(migration_data["max_cpu_rate"].describe())

CPU rate:
count    2.520771e+06
mean     1.745435e-02
std      3.560219e-02
min      0.000000e+00
25%      1.936000e-04
50%      1.221000e-03
75%      1.981000e-02
max      5.332000e-01
Name: cpu_rate, dtype: float64

Canonical memory:
count    2.520771e+06
mean     1.904364e-02
std      3.386105e-02
min      0.000000e+00
25%      6.104000e-04
50%      4.425000e-03
75%      2.167000e-02
max      7.520000e-01
Name: canonical_memory_usage, dtype: float64

Max CPU rate:
count    2.520771e+06
mean     7.022997e-02
std      1.084387e-01
min      0.000000e+00
25%      7.229000e-04
50%      1.581000e-02
75%      1.046000e-01
max      1.436000e+01
Name: max_cpu_rate, dtype: float64

In [37]:
print("Tasks with >50 records:", (task_record_counts > 50).sum())
print("Tasks with >100 records:", (task_record_counts > 100).sum())
print("Tasks with >200 records:", (task_record_counts > 200).sum())

Tasks with >50 records: 4
Tasks with >100 records: 1
Tasks with >200 records: 1

In [38]:
task_summary = migration_data.groupby("task_id").agg(
    avg_cpu=("cpu_rate", "mean"),
    max_cpu=("max_cpu_rate", "max"),
    avg_memory=("canonical_memory_usage", "mean"),
    max_memory=("max_memory_usage", "max"),
    avg_disk_io=("mean_disk_io_time", "mean"),
    duration_seconds=("duration_seconds", "sum")
).reset_index()

print(task_summary.head())
print("\nShape:", task_summary.shape)

        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   duration_seconds
0            5100.0
1            5100.0
2            5100.0
3            5100.0
4            5100.0

Shape: (179427, 7)

In [39]:
task_lifetime = migration_data.groupby("task_id").agg(
    first_start=("start_time", "min"),
    last_end=("end_time", "max")
).reset_index()

task_lifetime["lifetime_seconds"] = (
    task_lifetime["last_end"] - task_lifetime["first_start"]
) / 1_000_000

print(task_lifetime.head())
print("\nLifetime statistics:")
print(task_lifetime["lifetime_seconds"].describe())

        task_id  first_start    last_end  lifetime_seconds
0  1005190908_0    600000000  5700000000            5100.0
1  1005190908_1    600000000  5700000000            5100.0
2  1005190908_2    600000000  5700000000            5100.0
3  1005190908_3    600000000  5700000000            5100.0
4  1005190908_4    600000000  5700000000            5100.0

Lifetime statistics:
count    179427.000000
mean       3829.082563
std        2030.148304
min           2.000000
25%        1626.000000
50%        5100.000000
75%        5100.000000
max        5100.000000
Name: lifetime_seconds, dtype: float64

In [40]:
task_summary = task_summary.drop(columns=["duration_seconds"])

task_summary = task_summary.merge(
    task_lifetime[["task_id", "lifetime_seconds"]],
    on="task_id",
    how="left"
)

print(task_summary.head())
print("\nShape:", task_summary.shape)

        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds
0            5100.0
1            5100.0
2            5100.0
3            5100.0
4            5100.0

Shape: (179427, 7)

In [41]:
cpu_variability = migration_data.groupby("task_id").agg(
    cpu_std=("cpu_rate", "std")
).reset_index()

task_summary = task_summary.merge(
    cpu_variability,
    on="task_id",
    how="left"
)

print(task_summary.head())
print("\nCPU variability statistics:")
print(task_summary["cpu_std"].describe())

        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds   cpu_std
0            5100.0  0.000033
1            5100.0  0.000021
2            5100.0  0.000051
3            5100.0  0.000035
4            5100.0  0.000053

CPU variability statistics:
count    179305.000000
mean          0.010997
std           0.020049
min           0.000000
25%           0.000008
50%           0.002126
75%           0.012026
max           0.165195
Name: cpu_std, dtype: float64

In [42]:
task_summary["cpu_std"] = task_summary["cpu_std"].fillna(0)

print("Missing cpu_std:", task_summary["cpu_std"].isna().sum())
print(task_summary["cpu_std"].describe())

Missing cpu_std: 0
count    179427.000000
mean          0.010990
std           0.020044
min           0.000000
25%           0.000008
50%           0.002121
75%           0.012008
max           0.165195
Name: cpu_std, dtype: float64

In [43]:
memory_variability = migration_data.groupby("task_id").agg(
    memory_std=("canonical_memory_usage", "std")
).reset_index()

task_summary = task_summary.merge(
    memory_variability,
    on="task_id",
    how="left"
)

task_summary["memory_std"] = task_summary["memory_std"].fillna(0)

print(task_summary.head())
print("\nMemory variability statistics:")
print(task_summary["memory_std"].describe())

        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds   cpu_std    memory_std
0            5100.0  0.000033  7.125967e-07
1            5100.0  0.000021  1.213587e-06
2            5100.0  0.000051  8.110451e-07
3            5100.0  0.000035  1.484305e-06
4            5100.0  0.000053  9.359251e-07

Memory variability statistics:
count    179427.000000
mean          0.002332
std           0.005771
min           0.000000
25%           0.000005
50%           0.000245
75%           0.002077
max           0.101405
Name: memory_std, dtype: float64

In [44]:
observation_counts = migration_data.groupby("task_id").size().reset_index(
    name="num_observations"
)

task_summary = task_summary.merge(
    observation_counts,
    on="task_id",
    how="left"
)

print(task_summary.head())
print("\nObservation count statistics:")
print(task_summary["num_observations"].describe())

        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds   cpu_std    memory_std  num_observations
0            5100.0  0.000033  7.125967e-07                17
1            5100.0  0.000021  1.213587e-06                17
2            5100.0  0.000051  8.110451e-07                17
3            5100.0  0.000035  1.484305e-06                17
4            5100.0  0.000053  9.359251e-07                17

Observation count statistics:
count    179427.000000
mean         14.049006
std           5.639122
min           1.000000
25%           9.500000
50%          17.000000
75%          17.000000
max         429.000000
Name: num_observations, dtype: float64

In [45]:
print(task_summary.isnull().sum())

task_id             0
avg_cpu             0
max_cpu             0
avg_memory          0
max_memory          0
avg_disk_io         0
lifetime_seconds    0
cpu_std             0
memory_std          0
num_observations    0
dtype: int64

In [46]:
print("Total missing values:", task_summary.isnull().sum().sum())
print("\nMissing values by column:")
print(task_summary.isnull().sum())

Total missing values: 0

Missing values by column:
task_id             0
avg_cpu             0
max_cpu             0
avg_memory          0
max_memory          0
avg_disk_io         0
lifetime_seconds    0
cpu_std             0
memory_std          0
num_observations    0
dtype: int64

In [47]:
print(task_summary.columns.tolist())
print("\nShape:", task_summary.shape)

['task_id', 'avg_cpu', 'max_cpu', 'avg_memory', 'max_memory', 'avg_disk_io', 'lifetime_seconds', 'cpu_std', 'memory_std', 'num_observations']

Shape: (179427, 10)

In [48]:
task_summary.to_csv("task_summary_checkpoint.csv", index=False)

print("Checkpoint saved successfully.")

Checkpoint saved successfully.

In [49]:
import pandas as pd

task_events = pd.read_csv(
    "task_events/part-00000-of-00500.csv.gz",
    header=None
)

print("Shape:", task_events.shape)
print("\nFirst 5 rows:")
display(task_events.head())

Shape: (450146, 13)

First 5 rows:

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0,2.0,3418309,0,4.155527e+09,0,70s3v5qRyCO/1PCdI6fVXnrW8FU/w+5CKRSa72xgcIo=,3,9,NaN,NaN,NaN,NaN
1,0,2.0,3418309,1,3.291507e+08,0,70s3v5qRyCO/1PCdI6fVXnrW8FU/w+5CKRSa72xgcIo=,3,9,NaN,NaN,NaN,NaN
2,0,NaN,3418314,0,3.938719e+09,0,70s3v5qRyCO/1PCdI6fVXnrW8FU/w+5CKRSa72xgcIo=,3,9,0.125,0.07446,0.000424,0.0
3,0,NaN,3418314,1,3.516186e+08,0,70s3v5qRyCO/1PCdI6fVXnrW8FU/w+5CKRSa72xgcIo=,3,9,0.125,0.07446,0.000424,0.0
4,0,2.0,3418319,0,4.310529e+08,0,70s3v5qRyCO/1PCdI6fVXnrW8FU/w+5CKRSa72xgcIo=,3,9,NaN,NaN,NaN,NaN

In [50]:
task_events.columns = [
    "timestamp",
    "missing_info",
    "job_id",
    "task_index",
    "machine_id",
    "event_type",
    "user_name",
    "scheduling_class",
    "priority",
    "cpu_request",
    "ram_request",
    "disk_request",
    "different_machine_constraint"
]

print("Columns:")
print(task_events.columns.tolist())

print("\nShape:", task_events.shape)

Columns:
['timestamp', 'missing_info', 'job_id', 'task_index', 'machine_id', 'event_type', 'user_name', 'scheduling_class', 'priority', 'cpu_request', 'ram_request', 'disk_request', 'different_machine_constraint']

Shape: (450146, 13)

In [51]:
print(task_events.dtypes)

timestamp                         int64
missing_info                    float64
job_id                            int64
task_index                        int64
machine_id                      float64
event_type                        int64
user_name                        object
scheduling_class                  int64
priority                          int64
cpu_request                     float64
ram_request                     float64
disk_request                    float64
different_machine_constraint    float64
dtype: object

In [52]:
missing = task_events.isnull().sum()

print(missing)

timestamp                            0
missing_info                    449855
job_id                               0
task_index                           0
machine_id                      119565
event_type                           0
user_name                            0
scheduling_class                     0
priority                             0
cpu_request                        291
ram_request                        291
disk_request                       291
different_machine_constraint       291
dtype: int64

In [53]:
print(task_events["missing_info"].value_counts(dropna=False))

missing_info
NaN    449855
2.0       291
Name: count, dtype: int64

In [54]:
print(task_events["event_type"].value_counts().sort_index())

event_type
0    201491
1    189994
2      4338
3       581
4     43237
5     10505
Name: count, dtype: int64

In [55]:
print(task_events[["event_type", "job_id", "task_index", "machine_id"]].head(20))

    event_type   job_id  task_index    machine_id
0            0  3418309           0  4.155527e+09
1            0  3418309           1  3.291507e+08
2            0  3418314           0  3.938719e+09
3            0  3418314           1  3.516186e+08
4            0  3418319           0  4.310529e+08
5            0  3418319           1  2.573488e+08
6            0  3418324           0  5.655258e+09
7            0  3418324           1  3.550322e+09
8            0  3418329           0  1.303745e+06
9            0  3418329           1  3.894543e+09
10           0  3418329           2  3.360257e+08
11           0  3418334           0  3.405237e+09
12           0  3418334           1  4.310814e+08
13           0  3418339           0  8.489965e+07
14           0  3418339           1  1.268205e+06
15           0  3418339           2  7.753127e+06
16           0  3418339           3  3.516213e+08
17           0  3418339           4  3.174887e+08
18           0  3418339           5  2.595184e+09
19           0  3418339           6  6.215889e+08

In [56]:
# Display the number of records for each event type
event_counts = task_events["event_type"].value_counts().sort_index()

display(event_counts.to_frame("record_count"))

            record_count
event_type
0                 201491
1                 189994
2                   4338
3                    581
4                  43237
5                  10505

In [57]:
task_events["task_id"] = (
    task_events["job_id"].astype(str)
    + "_"
    + task_events["task_index"].astype(str)
)

print("Unique task IDs:", task_events["task_id"].nunique())
print("Total event records:", len(task_events))

event_counts_per_task = task_events.groupby("task_id").size()

print("\nEvent records per task:")
print(event_counts_per_task.describe())

Unique task IDs: 190926
Total event records: 450146

Event records per task:
count    190926.000000
mean          2.357699
std           6.502772
min           1.000000
25%           2.000000
50%           2.000000
75%           3.000000
max         550.000000
dtype: float64

In [58]:
common_tasks = set(task_summary["task_id"]).intersection(
    set(task_events["task_id"])
)

print("Tasks in task_summary:", task_summary["task_id"].nunique())
print("Tasks in task_events:", task_events["task_id"].nunique())
print("Tasks common to both:", len(common_tasks))

Tasks in task_summary: 179427
Tasks in task_events: 190926
Tasks common to both: 179427

In [59]:
event_counts = (
    task_events.groupby("task_id")
    .size()
    .reset_index(name="num_events")
)

print("Shape:", event_counts.shape)
display(event_counts.head())

Shape: (190926, 2)

        task_id  num_events
0  1005190908_0           2
1  1005190908_1           2
2  1005190908_2           2
3  1005190908_3           2
4  1005190908_4           2

In [60]:
task_summary = task_summary.merge(
    event_counts,
    on="task_id",
    how="left"
)

print("Shape:", task_summary.shape)
print("\nColumns:")
print(task_summary.columns.tolist())

print("\nMissing num_events:")
print(task_summary["num_events"].isnull().sum())

Shape: (179427, 11)

Columns:
['task_id', 'avg_cpu', 'max_cpu', 'avg_memory', 'max_memory', 'avg_disk_io', 'lifetime_seconds', 'cpu_std', 'memory_std', 'num_observations', 'num_events']

Missing num_events:
0

In [61]:
display(task_summary.head())

,task_id,avg_cpu,max_cpu,avg_memory,max_memory,avg_disk_io,lifetime_seconds,cpu_std,memory_std,num_observations,num_events
0,1005190908_0,0.001985,0.06274,0.000951,0.000956,0.000008,5100.0,0.000033,7.125967e-07,17,2
1,1005190908_1,0.001742,0.05322,0.000820,0.000824,0.000012,5100.0,0.000021,1.213587e-06,17,2
2,1005190908_2,0.001785,0.06567,0.000950,0.000971,0.000009,5100.0,0.000051,8.110451e-07,17,2
3,1005190908_3,0.002113,0.06262,0.000992,0.001005,0.000007,5100.0,0.000035,1.484305e-06,17,2
4,1005190908_4,0.001838,0.06250,0.000900,0.000913,0.000007,5100.0,0.000053,9.359251e-07,17,2

In [62]:
print(task_summary.dtypes)

task_id              object
avg_cpu             float64
max_cpu             float64
avg_memory          float64
max_memory          float64
avg_disk_io         float64
lifetime_seconds    float64
cpu_std             float64
memory_std          float64
num_observations      int64
num_events            int64
dtype: object

In [63]:
task_summary.to_csv("task_summary_with_events.csv", index=False)

print("Saved successfully!")
print("Shape:", task_summary.shape)

Saved successfully!
Shape: (179427, 11)

In [64]:
print(task_events[
    ["cpu_request", "ram_request", "disk_request"]
].describe())

         cpu_request    ram_request   disk_request
count  449855.000000  449855.000000  449855.000000
mean        0.044100       0.036062       0.000333
std         0.047539       0.038031       0.000401
min         0.000000       0.000000       0.000000
25%         0.015620       0.015530       0.000070
50%         0.024990       0.025450       0.000386
75%         0.062500       0.038210       0.000386
max         0.500000       0.955100       0.009720

In [65]:
print(task_events["priority"].value_counts().sort_index())

priority
0     119711
1      35733
2     173736
8       7013
9      99178
10      1688
11     13087
Name: count, dtype: int64

In [66]:
print(task_events["scheduling_class"].value_counts().sort_index())

scheduling_class
0    237969
1     58109
2     97482
3     56586
Name: count, dtype: int64

In [67]:
print("Unique users:", task_events["user_name"].nunique())

Unique users: 519

In [71]:
import pandas as pd

machine_events = pd.read_csv(
    "machine_events/part-00000-of-00001.csv.gz",
    header=None
)

print(machine_events.shape)
print(machine_events.head())

(37780, 6)
   0   1  2                                             3    4       5
0  0   5  0  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=  0.5  0.2493
1  0   6  0  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=  0.5  0.2493
2  0   7  0  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=  0.5  0.2493
3  0  10  0  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=  0.5  0.2493
4  0  13  0  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=  0.5  0.2493

In [72]:
machine_events.columns = [
    "timestamp",
    "machine_id",
    "event_type",
    "platform_id",
    "cpu_capacity",
    "memory_capacity"
]

print(machine_events.head())
print(machine_events.dtypes)

   timestamp  machine_id  event_type  \
0          0           5           0
1          0           6           0
2          0           7           0
3          0          10           0
4          0          13           0

                                    platform_id  cpu_capacity  memory_capacity
0  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=           0.5           0.2493
1  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=           0.5           0.2493
2  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=           0.5           0.2493
3  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=           0.5           0.2493
4  HofLGzk1Or/8Ildj2+Lqv0UGGvY82NLoni8+J/Yy0RU=           0.5           0.2493
timestamp            int64
machine_id           int64
event_type           int64
platform_id         object
cpu_capacity       float64
memory_capacity    float64
dtype: object

In [73]:
print(machine_events["event_type"].value_counts().sort_index())

event_type
0    21443
1     8957
2     7380
Name: count, dtype: int64

In [74]:
print("Unique machines:", machine_events["machine_id"].nunique())
print("Unique CPU capacities:", machine_events["cpu_capacity"].nunique())
print("Unique memory capacities:", machine_events["memory_capacity"].nunique())

Unique machines: 12583
Unique CPU capacities: 3
Unique memory capacities: 10

In [75]:
print("CPU capacity values:")
print(sorted(machine_events["cpu_capacity"].unique()))

print("\nMemory capacity values:")
print(sorted(machine_events["memory_capacity"].unique()))

CPU capacity values:
[np.float64(0.25), np.float64(0.5), np.float64(1.0), np.float64(nan)]

Memory capacity values:
[np.float64(0.03085), np.float64(0.06158), np.float64(0.1241), np.float64(0.2493), np.float64(0.2498), np.float64(0.4995), np.float64(0.5), np.float64(0.749), np.float64(0.9678), np.float64(1.0), np.float64(nan)]

In [76]:
print("Missing CPU capacity:", machine_events["cpu_capacity"].isna().sum())
print("Missing memory capacity:", machine_events["memory_capacity"].isna().sum())
print("Missing platform ID:", machine_events["platform_id"].isna().sum())

Missing CPU capacity: 32
Missing memory capacity: 32
Missing platform ID: 0

In [77]:
machine_event_counts = (
    machine_events.groupby("machine_id")
    .size()
    .reset_index(name="num_machine_events")
)

print(machine_event_counts["num_machine_events"].describe())

count    12583.000000
mean         3.002464
std          6.098154
min          1.000000
25%          1.000000
50%          1.000000
75%          3.000000
max        330.000000
Name: num_machine_events, dtype: float64

In [78]:
machine_capacity = (
    machine_events
    .groupby("machine_id")
    .agg(
        cpu_capacity=("cpu_capacity", "first"),
        memory_capacity=("memory_capacity", "first")
    )
    .reset_index()
)

print(machine_capacity.shape)
print(machine_capacity.head())

(12583, 3)
   machine_id  cpu_capacity  memory_capacity
0           5           0.5           0.2493
1           6           0.5           0.2493
2           7           0.5           0.2493
3          10           0.5           0.2493
4          13           0.5           0.2493

In [79]:
migration_data = migration_data.merge(
    machine_capacity,
    on="machine_id",
    how="left"
)

print(migration_data.shape)
print(migration_data[[
    "machine_id",
    "cpu_capacity",
    "memory_capacity"
]].head())

(2520771, 22)
   machine_id  cpu_capacity  memory_capacity
0  4155527081           0.5           0.2493
1   329150663           0.5           0.2493
2  3938719206           0.5           0.4995
3   351618647           0.5           0.4995
4   431052910           0.5           0.4995

In [80]:
print("Missing CPU capacity:", migration_data["cpu_capacity"].isna().sum())
print("Missing memory capacity:", migration_data["memory_capacity"].isna().sum())

Missing CPU capacity: 0
Missing memory capacity: 0

In [81]:
print("Shape:", migration_data.shape)
print("\nColumns:")
print(migration_data.columns.tolist())

Shape: (2520771, 22)

Columns:
['start_time', 'end_time', 'job_id', 'task_index', 'machine_id', 'cpu_rate', 'canonical_memory_usage', 'assigned_memory_usage', 'unmapped_page_cache', 'total_page_cache', 'max_memory_usage', 'mean_disk_io_time', 'mean_local_disk_space', 'max_cpu_rate', 'sampling_portion', 'aggregation_type', 'sampled_cpu_usage', 'duration_seconds', 'time_hours', 'task_id', 'cpu_capacity', 'memory_capacity']

In [83]:
migration_data.to_csv(
    "migration_data_checkpoint.csv",
    index=False
)

print("Saved:", len(migration_data), "rows")

Saved: 2520771 rows

In [84]:
task_machine = (
    migration_data[["task_id", "machine_id"]]
    .drop_duplicates("task_id")
)

task_summary = task_summary.merge(
    task_machine,
    on="task_id",
    how="left"
)

print("Shape:", task_summary.shape)
print(task_summary.head())

Shape: (179427, 12)
        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds   cpu_std    memory_std  num_observations  num_events  \
0            5100.0  0.000033  7.125967e-07                17           2
1            5100.0  0.000021  1.213587e-06                17           2
2            5100.0  0.000051  8.110451e-07                17           2
3            5100.0  0.000035  1.484305e-06                17           2
4            5100.0  0.000053  9.359251e-07                17           2

   machine_id
0   554338230
1   554448185
2   351612866
3  2786825979
4  3630655861

In [85]:
task_summary = task_summary.merge(
    machine_capacity,
    on="machine_id",
    how="left"
)

print("Shape:", task_summary.shape)
print(task_summary.head())

Shape: (179427, 14)
        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds   cpu_std    memory_std  num_observations  num_events  \
0            5100.0  0.000033  7.125967e-07                17           2
1            5100.0  0.000021  1.213587e-06                17           2
2            5100.0  0.000051  8.110451e-07                17           2
3            5100.0  0.000035  1.484305e-06                17           2
4            5100.0  0.000053  9.359251e-07                17           2

   machine_id  cpu_capacity  memory_capacity
0   554338230          0.50           0.4995
1   554448185          0.50           0.2493
2   351612866          0.50           0.4995
3  2786825979          0.50           0.4995
4  3630655861          0.25           0.2498

In [86]:
task_event_summary = (
    task_events.groupby("task_id")
    .agg(
        priority=("priority", "first"),
        scheduling_class=("scheduling_class", "first")
    )
    .reset_index()
)

print("Shape:", task_event_summary.shape)
print(task_event_summary.head())

Shape: (190926, 3)
        task_id  priority  scheduling_class
0  1005190908_0        10                 2
1  1005190908_1        10                 2
2  1005190908_2        10                 2
3  1005190908_3        10                 2
4  1005190908_4        10                 2

In [87]:
task_summary = task_summary.merge(
    task_event_summary,
    on="task_id",
    how="left"
)

print("Shape:", task_summary.shape)
print(task_summary.head())
print("\nMissing priority:", task_summary["priority"].isna().sum())
print("Missing scheduling class:", task_summary["scheduling_class"].isna().sum())

Shape: (179427, 16)
        task_id   avg_cpu  max_cpu  avg_memory  max_memory  avg_disk_io  \
0  1005190908_0  0.001985  0.06274    0.000951    0.000956     0.000008
1  1005190908_1  0.001742  0.05322    0.000820    0.000824     0.000012
2  1005190908_2  0.001785  0.06567    0.000950    0.000971     0.000009
3  1005190908_3  0.002113  0.06262    0.000992    0.001005     0.000007
4  1005190908_4  0.001838  0.06250    0.000900    0.000913     0.000007

   lifetime_seconds   cpu_std    memory_std  num_observations  num_events  \
0            5100.0  0.000033  7.125967e-07                17           2
1            5100.0  0.000021  1.213587e-06                17           2
2            5100.0  0.000051  8.110451e-07                17           2
3            5100.0  0.000035  1.484305e-06                17           2
4            5100.0  0.000053  9.359251e-07                17           2

   machine_id  cpu_capacity  memory_capacity  priority  scheduling_class
0   554338230          0.50           0.4995        10                 2
1   554448185          0.50           0.2493        10                 2
2   351612866          0.50           0.4995        10                 2
3  2786825979          0.50           0.4995        10                 2
4  3630655861          0.25           0.2498        10                 2

Missing priority: 0
Missing scheduling class: 0

In [88]:
task_summary.to_csv(
    "task_summary_full.csv",
    index=False
)

print("Saved:", len(task_summary), "tasks")

Saved: 179427 tasks

In [89]:
task_summary["cpu_utilization_ratio"] = (
    task_summary["avg_cpu"] / task_summary["cpu_capacity"]
)

print(task_summary[
    ["avg_cpu", "cpu_capacity", "cpu_utilization_ratio"]
].head())

print("\nCPU utilization statistics:")
print(task_summary["cpu_utilization_ratio"].describe())

    avg_cpu  cpu_capacity  cpu_utilization_ratio
0  0.001985          0.50               0.003970
1  0.001742          0.50               0.003483
2  0.001785          0.50               0.003570
3  0.002113          0.50               0.004227
4  0.001838          0.25               0.007354

CPU utilization statistics:
count    179427.000000
mean          0.033541
std           0.057203
min           0.000000
25%           0.000415
50%           0.009390
75%           0.041009
max           0.690141
Name: cpu_utilization_ratio, dtype: float64

In [90]:
task_summary["memory_utilization_ratio"] = (
    task_summary["avg_memory"] / task_summary["memory_capacity"]
)

print(task_summary[
    ["avg_memory", "memory_capacity", "memory_utilization_ratio"]
].head())

print("\nMemory utilization statistics:")
print(task_summary["memory_utilization_ratio"].describe())

   avg_memory  memory_capacity  memory_utilization_ratio
0    0.000951           0.4995                  0.001904
1    0.000820           0.2493                  0.003290
2    0.000950           0.4995                  0.001901
3    0.000992           0.4995                  0.001986
4    0.000900           0.2498                  0.003603

Memory utilization statistics:
count    179427.000000
mean          0.036111
std           0.067905
min           0.000000
25%           0.002016
50%           0.008395
75%           0.040315
max           0.854793
Name: memory_utilization_ratio, dtype: float64

In [91]:
task_summary["cpu_headroom"] = (
    1 - task_summary["cpu_utilization_ratio"]
)

print(task_summary[
    ["cpu_utilization_ratio", "cpu_headroom"]
].head())

print("\nCPU headroom statistics:")
print(task_summary["cpu_headroom"].describe())

   cpu_utilization_ratio  cpu_headroom
0               0.003970      0.996030
1               0.003483      0.996517
2               0.003570      0.996430
3               0.004227      0.995773
4               0.007354      0.992646

CPU headroom statistics:
count    179427.000000
mean          0.966459
std           0.057203
min           0.309859
25%           0.958991
50%           0.990610
75%           0.999585
max           1.000000
Name: cpu_headroom, dtype: float64

In [92]:
task_summary["memory_headroom"] = (
    1 - task_summary["memory_utilization_ratio"]
)

print(task_summary[
    ["memory_utilization_ratio", "memory_headroom"]
].head())

print("\nMemory headroom statistics:")
print(task_summary["memory_headroom"].describe())

   memory_utilization_ratio  memory_headroom
0                  0.001904         0.998096
1                  0.003290         0.996710
2                  0.001901         0.998099
3                  0.001986         0.998014
4                  0.003603         0.996397

Memory headroom statistics:
count    179427.000000
mean          0.963889
std           0.067905
min           0.145207
25%           0.959685
50%           0.991605
75%           0.997984
max           1.000000
Name: memory_headroom, dtype: float64

In [93]:
task_summary["overall_resource_utilization"] = (
    task_summary["cpu_utilization_ratio"] +
    task_summary["memory_utilization_ratio"]
) / 2

print(task_summary[
    [
        "cpu_utilization_ratio",
        "memory_utilization_ratio",
        "overall_resource_utilization"
    ]
].head())

print("\nOverall resource utilization statistics:")
print(task_summary["overall_resource_utilization"].describe())

   cpu_utilization_ratio  memory_utilization_ratio  \
0               0.003970                  0.001904
1               0.003483                  0.003290
2               0.003570                  0.001901
3               0.004227                  0.001986
4               0.007354                  0.003603

   overall_resource_utilization
0                      0.002937
1                      0.003387
2                      0.002735
3                      0.003106
4                      0.005478

Overall resource utilization statistics:
count    179427.000000
mean          0.034826
std           0.051366
min           0.000000
25%           0.001681
50%           0.016068
75%           0.047447
max           0.578482
Name: overall_resource_utilization, dtype: float64

In [94]:
priority_consistency = (
    task_events.groupby("task_id")["priority"]
    .nunique()
)

print("Tasks with exactly one priority:")
print((priority_consistency == 1).sum())

print("\nTasks with multiple priorities:")
print((priority_consistency > 1).sum())

Tasks with exactly one priority:
190926

Tasks with multiple priorities:
0

In [95]:
scheduling_consistency = (
    task_events.groupby("task_id")["scheduling_class"]
    .nunique()
)

print("Tasks with exactly one scheduling class:")
print((scheduling_consistency == 1).sum())

print("\nTasks with multiple scheduling classes:")
print((scheduling_consistency > 1).sum())

Tasks with exactly one scheduling class:
190926

Tasks with multiple scheduling classes:
0

In [96]:
print("Tasks with CPU utilization > 0.5:")
print(
    (task_summary["cpu_utilization_ratio"] > 0.5).sum()
)

print("\nTasks with CPU utilization > 0.8:")
print(
    (task_summary["cpu_utilization_ratio"] > 0.8).sum()
)

print("\nTasks with CPU utilization > 1.0:")
print(
    (task_summary["cpu_utilization_ratio"] > 1.0).sum()
)

Tasks with CPU utilization > 0.5:
216

Tasks with CPU utilization > 0.8:
0

Tasks with CPU utilization > 1.0:
0

In [97]:
print("Tasks with memory utilization > 0.5:")
print(
    (task_summary["memory_utilization_ratio"] > 0.5).sum()
)

print("\nTasks with memory utilization > 0.8:")
print(
    (task_summary["memory_utilization_ratio"] > 0.8).sum()
)

print("\nTasks with memory utilization > 1.0:")
print(
    (task_summary["memory_utilization_ratio"] > 1.0).sum()
)

Tasks with memory utilization > 0.5:
379

Tasks with memory utilization > 0.8:
1

Tasks with memory utilization > 1.0:
0

In [98]:
important_features = [
    "avg_cpu",
    "max_cpu",
    "avg_memory",
    "max_memory",
    "avg_disk_io",
    "lifetime_seconds",
    "cpu_std",
    "memory_std",
    "num_observations",
    "num_events",
    "cpu_capacity",
    "memory_capacity",
    "priority",
    "scheduling_class",
    "cpu_utilization_ratio",
    "memory_utilization_ratio",
    "cpu_headroom",
    "memory_headroom",
    "overall_resource_utilization"
]

missing_features = task_summary[important_features].isnull().sum()

print(missing_features)

avg_cpu                         0
max_cpu                         0
avg_memory                      0
max_memory                      0
avg_disk_io                     0
lifetime_seconds                0
cpu_std                         0
memory_std                      0
num_observations                0
num_events                      0
cpu_capacity                    0
memory_capacity                 0
priority                        0
scheduling_class                0
cpu_utilization_ratio           0
memory_utilization_ratio        0
cpu_headroom                    0
memory_headroom                 0
overall_resource_utilization    0
dtype: int64

In [99]:
task_summary.to_csv(
    "task_summary_ml_ready.csv",
    index=False
)

print("Saved:", len(task_summary), "tasks")
print("Columns:", len(task_summary.columns))
print("\nFile: task_summary_ml_ready.csv")

Saved: 179427 tasks
Columns: 21

File: task_summary_ml_ready.csv

In [100]:
print("Final task-level columns:\n")

for i, column in enumerate(task_summary.columns, start=1):
    print(f"{i}. {column}")

Final task-level columns:

1. task_id
2. avg_cpu
3. max_cpu
4. avg_memory
5. max_memory
6. avg_disk_io
7. lifetime_seconds
8. cpu_std
9. memory_std
10. num_observations
11. num_events
12. machine_id
13. cpu_capacity
14. memory_capacity
15. priority
16. scheduling_class
17. cpu_utilization_ratio
18. memory_utilization_ratio
19. cpu_headroom
20. memory_headroom
21. overall_resource_utilization

In [101]:
ml_features = [
    "avg_cpu",
    "max_cpu",
    "avg_memory",
    "max_memory",
    "avg_disk_io",
    "lifetime_seconds",
    "cpu_std",
    "memory_std",
    "num_observations",
    "num_events",
    "cpu_capacity",
    "memory_capacity",
    "priority",
    "scheduling_class",
    "cpu_utilization_ratio",
    "memory_utilization_ratio",
    "cpu_headroom",
    "memory_headroom",
    "overall_resource_utilization"
]

X = task_summary[ml_features].copy()

print("ML feature matrix shape:", X.shape)
print("\nNumber of features:", len(ml_features))
print("\nFeatures:")
print(ml_features)

ML feature matrix shape: (179427, 19)

Number of features: 19

Features:
['avg_cpu', 'max_cpu', 'avg_memory', 'max_memory', 'avg_disk_io', 'lifetime_seconds', 'cpu_std', 'memory_std', 'num_observations', 'num_events', 'cpu_capacity', 'memory_capacity', 'priority', 'scheduling_class', 'cpu_utilization_ratio', 'memory_utilization_ratio', 'cpu_headroom', 'memory_headroom', 'overall_resource_utilization']

In [102]:
correlation_matrix = X.corr()

print(
    correlation_matrix[
        ["cpu_utilization_ratio",
         "memory_utilization_ratio",
         "overall_resource_utilization"]
    ].round(3)
)

                              cpu_utilization_ratio  memory_utilization_ratio  \
avg_cpu                                       0.983                     0.337
max_cpu                                       0.628                     0.270
avg_memory                                    0.303                     0.906
max_memory                                    0.417                     0.861
avg_disk_io                                   0.209                     0.048
lifetime_seconds                             -0.036                     0.229
cpu_std                                       0.592                     0.023
memory_std                                    0.441                     0.100
num_observations                             -0.007                     0.196
num_events                                    0.014                    -0.106
cpu_capacity                                 -0.084                    -0.042
memory_capacity                              -0.040                    -0.075
priority                                      0.258                     0.439
scheduling_class                              0.122                     0.439
cpu_utilization_ratio                         1.000                     0.344
memory_utilization_ratio                      0.344                     1.000
cpu_headroom                                 -1.000                    -0.344
memory_headroom                              -0.344                    -1.000
overall_resource_utilization                  0.784                     0.852

                              overall_resource_utilization
avg_cpu                                              0.770
max_cpu                                              0.528
avg_memory                                           0.768
max_memory                                           0.802
avg_disk_io                                          0.148
lifetime_seconds                                     0.132
cpu_std                                              0.345
memory_std                                           0.312
num_observations                                     0.125
num_events                                          -0.062
cpu_capacity                                        -0.074
memory_capacity                                     -0.072
priority                                             0.434
scheduling_class                                     0.358
cpu_utilization_ratio                                0.784
memory_utilization_ratio                             0.852
cpu_headroom                                        -0.784
memory_headroom                                     -0.852
overall_resource_utilization                         1.000

In [103]:
corr_pairs = (
    correlation_matrix
    .where(
        ~__import__("numpy").tril(
            __import__("numpy").ones(correlation_matrix.shape),
            k=0
        ).astype(bool)
    )
    .stack()
    .sort_values(key=abs, ascending=False)
)

print("Feature pairs with |correlation| >= 0.90:\n")

print(
    corr_pairs[corr_pairs.abs() >= 0.90]
)

Feature pairs with |correlation| >= 0.90:

cpu_utilization_ratio     cpu_headroom               -1.000000
memory_utilization_ratio  memory_headroom            -1.000000
avg_cpu                   cpu_headroom               -0.983067
                          cpu_utilization_ratio       0.983067
avg_memory                max_memory                  0.955922
lifetime_seconds          num_observations            0.927703
avg_memory                memory_utilization_ratio    0.906495
                          memory_headroom            -0.906495
dtype: float64

In [104]:
high_corr = corr_pairs[corr_pairs.abs() >= 0.90].reset_index()

high_corr.columns = [
    "feature_1",
    "feature_2",
    "correlation"
]

print(high_corr)

                  feature_1                 feature_2  correlation
0     cpu_utilization_ratio              cpu_headroom    -1.000000
1  memory_utilization_ratio           memory_headroom    -1.000000
2                   avg_cpu              cpu_headroom    -0.983067
3                   avg_cpu     cpu_utilization_ratio     0.983067
4                avg_memory                max_memory     0.955922
5          lifetime_seconds          num_observations     0.927703
6                avg_memory  memory_utilization_ratio     0.906495
7                avg_memory           memory_headroom    -0.906495

In [105]:
selected_features = [
    "avg_cpu",
    "max_cpu",
    "avg_memory",
    "max_memory",
    "avg_disk_io",
    "lifetime_seconds",
    "cpu_std",
    "memory_std",
    "num_observations",
    "num_events",
    "cpu_capacity",
    "memory_capacity",
    "priority",
    "scheduling_class",
    "cpu_utilization_ratio",
    "memory_utilization_ratio"
]

X_selected = task_summary[selected_features].copy()

print("Selected feature matrix shape:", X_selected.shape)

print("\nSelected features:")
for i, feature in enumerate(selected_features, start=1):
    print(f"{i}. {feature}")

Selected feature matrix shape: (179427, 16)

Selected features:
1. avg_cpu
2. max_cpu
3. avg_memory
4. max_memory
5. avg_disk_io
6. lifetime_seconds
7. cpu_std
8. memory_std
9. num_observations
10. num_events
11. cpu_capacity
12. memory_capacity
13. priority
14. scheduling_class
15. cpu_utilization_ratio
16. memory_utilization_ratio

In [ ]:
processed_data.to_excel('/content/task.xlsx', index=False)